import React from "react";
import Head from "next/head";

const Http500 = () => {
	return (
		<>
			<Head>
				<title>500 error • Posts</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<h1>500 server error</h1>
		</>
	);
};

export default Http500;
