import React from "react";
import Head from "next/head";
import SettingsTemplate from "src/templates/profile/settings";
import AccountSettings from "src/templates/profile/settings/accountSettings";

export default function AccountSettingsPage() {
	return (
		<>
			<Head>
				<title>Account Settings • Posts</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<SettingsTemplate>
				<AccountSettings />
			</SettingsTemplate>
		</>
	);
}
