import React from "react";
import Head from "next/head";
import SettingsTemplate from "src/templates/profile/settings";
import ProfileSettings from "src/templates/profile/settings/profileSettings";
import cookie from "cookie";

export default function AccountProfilePage() {
	return (
		<>
			<Head>
				<title>Profile Settings • Posts</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<SettingsTemplate>
				<ProfileSettings />
			</SettingsTemplate>
		</>
	);
}

export async function getServerSideProps(context) {
	const { req, res } = context;
	const cookies = cookie.parse(req.headers.cookie || "");

	if (!cookies.auth) {
		res.writeHead(302, { Location: "/" });
		res.end();
	}

	return { props: {} };
}
